# Generated by Django 5.1.4 on 2024-12-11 20:12

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("price", models.FloatField(default=0)),
                ("photo", models.URLField(default="")),
                ("introduction_date", models.DateField(default=0)),
                ("producer", models.CharField(default="", max_length=100)),
                ("stock", models.IntegerField(default=0)),
                ("SKU", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TAB", "Tableware"),
                            ("CAT", "Coffee and Tea"),
                            ("DEC", "Decorations"),
                        ],
                        default="TAB",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("C", "Client"),
                            ("E", "Employee"),
                            ("A", "Administrator"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                ("wishlist", models.ManyToManyField(to="shop.product")),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField(default="")),
                ("amount", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pending"),
                            ("APY", "Awaiting Payment"),
                            ("APC", "Awaiting Pickup"),
                            ("SHI", "Shipped"),
                            ("CMP", "Completed"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "destination_country",
                    models.CharField(
                        choices=[
                            ("PL", "Poland"),
                            ("CZ", "Czech Republic"),
                            ("SL", "Slovak Republic"),
                            ("GE", "Germany"),
                        ],
                        default="PL",
                        max_length=12,
                    ),
                ),
                ("destination_region", models.CharField(default="", max_length=20)),
                ("destination_city", models.CharField(default="", max_length=20)),
                ("destination_postcode", models.CharField(default="", max_length=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CR", "Card")], default="CR", max_length=2
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("percentage", models.FloatField(default=0.0)),
                ("products", models.ManyToManyField(to="shop.product")),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order",
                    ),
                ),
                ("products", models.ManyToManyField(to="shop.product")),
            ],
        ),
    ]
