# Generated by Django 5.1.4 on 2024-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('position', models.CharField(choices=[('E', 'Employee'), ('A', 'Administrator')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Discount_percentage', models.FloatField(default=0.0)),
                ('start_date', models.DateField()),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
